### ISSUE TITLE
Use https:// version of Ares

### ISSUE THREAD

**Issue by illagrenan** [illagrenan/ares_util#12]
:exclamation: How to handle certificate errors?

**Comment by deadlydoge** [comment]
Hi! Can I help you with this error? I want to use your lib in my project. And I would like to have SSL connection.

**Comment by illagrenan** [comment]
Yes, PRs are very welcome :-) Back then, they were using a self-signed certificate. Now it looks like they have a proper certificate by DigiCert. I'll try to look at it this week.

**Comment by deadlydoge** [comment]
Hey man, thanks! I've tried some `curl` calls, and can say, their cert is ok.
