### ISSUE TITLE
Number of request per some time interval?

### ISSUE THREAD

**Issue by deadlydoge** [illagrenan/ares_util#51]
Hi,

did you do performance test? Does ARES portal has some time-outs or limitation?

I don't want to use it for some crawling staff. Just on-demand user's calls. And I don't want hit some time-out or ban from ARES's side.

Thank you,
DS

**Comment by illagrenan** [comment]
Check out these two documents (they are written in English):

* https://wwwinfo.mfcr.cz/ares/ares_xml.html.en
* https://wwwinfo.mfcr.cz/ares/ares_podminky.html.en

> ...
> 
> With respect to the nature of the ARES operation as well as to its security, the Ministry of Finance reserves the right to restrict or remove a user's access to those that: 
> 
> * make more than 10.000 inquiries in the period of 8 a.m. and 6 p.m.,
> * make more than 50.000 inquiries in the period of 6 p.m. one day and 8 a.m. the following day
> 
> ...

It is possible to write to them so they can increase these limits for you.
