### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by illagrenan** [illagrenan/ares_util#52]

**Comment by deadlydoge** [comment]
I've tried you lib on python3.7. Any issue. Or you know something?

**Comment by illagrenan** [comment]
I don't know of any problems. This package is very simple, works fine on Python 3.6, and there should be no problems with Python 3.7.

This issue is basically about:

* Update `setup.py` classifiers;
* Update CI to test on Python 3.7

**Comment by illagrenan** [comment]
Done in master.
