### ISSUE TITLE
Ares - street 

### ISSUE THREAD

**Issue by kyselak** [illagrenan/ares_util#9]
I still get zipcode in place of street name and zip_code is None, am I doing something wrong ?
For example this ICO 25834151 gives me:

{u'legal': {u'company_vat_id': u'CZ25834151', u'company_name': u'HELLA AUTOTECHNIK NOVA, s.r.o.', u'legal_form': u'112', u'company_id': u'25834151'}, u'address': {u'city': u'Mohelnice', u'region': None, u'street': u'PS\u010c 78985', u'city_part': None, u'zip_code': None}}

but the street part should be "Družstevní 338/16".

**Comment by illagrenan** [comment]
Thanks for report, I see this error. Give me few days for fix.

**Comment by illagrenan** [comment]
Fixed, new release is on PyPi.
